name = "ImplicitBVH"
uuid = "932a18dc-bb55-4cd5-bdd6-1368ec9cea29"
authors = ["Andrei Leonard Nicusan"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "0.9"
StaticArrays = "1.5"
julia = "1.7"
