name = "ImplicitBVH"
uuid = "932a18dc-bb55-4cd5-bdd6-1368ec9cea29"
authors = ["Andrei Leonard Nicusan"]
version = "0.4.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.9"
julia = "1.6"
